### ISSUE TITLE
res2无法获取的情况

### ISSUE THREAD

**Issue by liuyu5337** [longzhiwen888/fetch_baidu_index#10]
你好，请问res2获取不到是什么原因呢？

**Comment by longzhiwen888** [comment]
你看看你是借助的firefox登陆的吗？当时登陆成功了吗

**Comment by liuyu5337** [comment]
我使用的是phantomjs, 测试是登陆成功的。

**Comment by liuyu5337** [comment]
有时候开始可以获取res2,，抓取一段时间后就无法获取res2了

**Comment by longzhiwen888** [comment]
那就不太确定了，你用chrome浏览器登陆你的百度账号，在console里面输入return PPval.res2; 这些试试呢

**Comment by longzhiwen888** [comment]
输入PPval.ppt;  还有PPval.res2;  分别测试一下。你都用的哪几个关键词测试的？

**Comment by liuyu5337** [comment]
嗯，谢谢，我试试。另外execute_script(“return res;”)执行的脚本，这个是怎么知道的呢？我的意思对execute_script()这个方法里面的参数是怎么知道的。

**Comment by liuyu5337** [comment]
我使用的关键词有奥运会,欧洲杯等

**Comment by longzhiwen888** [comment]
你看看你出问题的关键词，用浏览器打开的时候有正常的数据吗？就是关键词在你指定的区间内有没有数据？没有数据的话可能会出问题吧。我那个PPval.res2跟PPval.ppt也是通过抓包后，把res跟res2的值在页面中查找到的。然后就想到通过控制台把他们打印出来。没有问题后，才把这个写到了执行js脚本

**Comment by liuyu5337** [comment]
Ok.我试试。我在页面看到的都是有数据的。有问题随时讨论：)
