### ISSUE TITLE
关于日期无法配置的情况

### ISSUE THREAD

**Issue by Boom247** [longzhiwen888/fetch_baidu_index#11]
博主~~为什么我在config里无论如何配置日期，最终导出的数据都是从2016-06-01到2016-06-30呀？

**Comment by Boom247** [comment]
可以啦可以啦~~只是还有一个问题是，为什么每次只能导出一个关键词的数据啊？当有多个数据是，好像数据会被下一个关键词的数据覆盖，最终只剩下一个关键词的数据

**Comment by longzhiwen888** [comment]
多个数据？不是关键词都在task.txt按行填写吗？结果文件应该也是根据关键词生成的吧

**Comment by Boom247** [comment]
的确是按行填写的呀，可是结果文件只能输出其中一个关键词的数据

**Comment by Boom247** [comment]
还有一个问题就是数据总是残缺不全的，有时候会漏掉一些日期的数据。。。不知道是为什么。。。

**Comment by longzhiwen888** [comment]
漏掉的数据可能是网络超时没有获取到，或者图片解析失败，图片解析失败的情况一般很少遇见。大多是网络问题的情况吧。你看看有没有执行报错的地方。可以给我截个图。发我邮箱 longzhiwen-478@163.com

**Comment by longzhiwen888** [comment]
你的关键词编码是utf8的吗？是不是编码的问题，我项目用的是utf8编码

**Comment by longzhiwen888** [comment]
如果还有问题的话，请把你的task.txt发到我邮箱，还有那个你说丢掉数据的excel结果文件

**Comment by Boom247** [comment]
啊。。。好像是我改动了您的一个地方导致了这个问题，我又把代码重新贴了一遍，问题就解决了。。。太感谢博主的耐心回答啦~~程序非常好用的说~

**Comment by longzhiwen888** [comment]
好吧，你可能是用变量把我那个关键词给覆盖了

**Comment by Boom247** [comment]
是呢~
不过不知道博主会不会出现下面这种问题呢？当时间间隔比较短的时候没有问题，但是当时间间隔比较长的时候，就总有一段数据缺失，我截取的是多个关键词2007-01-01到2016-06-30的数据，但是所有的数据都少了2011.01.01-2011.6.25中间这一段

**Comment by longzhiwen888** [comment]
你在百度指数里看到这段时间的数据有值吗？你说的2011.01.01-2011.6.25 这段。我今天更新一下代码，把下载数据的代码改成更可靠的。之前这段多线程代码是一个网友让我改的，就用了他的例子。

**Comment by Boom247** [comment]
我去查了百度指数的这段数据，是有值的~不知道是什么原因。。。好哒好哒~那我再下载更新一下是不是就可以啦？
