### ISSUE TITLE
地区

### ISSUE THREAD

**Issue by nkwu** [longzhiwen888/fetch_baidu_index#14]
请问有办法只输出某些省份的百度指数嘛？谢谢楼主。

**Comment by longzhiwen888** [comment]
可以输出省份的数据，你看我项目的配置文件config里面，有两个链接是带有  area=0 参数的，你把它替换成指定城市的链接就可以了，你自己在浏览器里面筛选城市可以看到城市的code值，替换一下我配置文件里面的
