### ISSUE TITLE
date specification

### ISSUE THREAD

**Issue by wdragon0207** [longzhiwen888/fetch_baidu_index#16]
First, great job!
But I do encounter some problem with the start and end date specification. It seems like the biggest range is from 2016-09-15 to 2016-09-16, which is a rather short range. I tried for a couple of keywords, it shows the same result.
I can't seem to change the dates either, even within the range.
Is there any way to get around that to get bigger range like starting from 2011?

**Comment by longzhiwen888** [comment]
If you set the start_date and end_date in config to empty, you can get the maximum time range for the keyword. @wdragon0207       You can view the browser.py 189 line
