### ISSUE TITLE
请求指导

### ISSUE THREAD

**Issue by jingbo1602** [longzhiwen888/fetch_baidu_index#18]
先感谢一下，您的工作成果！
我在某大学心理学系做助研，一直想拉百度指数的数据进行社会心理学研究，然后找到了您的程序。抱歉的是我并不懂编程，只能按图索骥一点一点尝试，但还是跑不通这个程序。不知道能否帮助我完美使用您的成果，先说声谢谢！
![error](https://cloud.githubusercontent.com/assets/24266451/20744413/d7996d20-b716-11e6-9416-b700db759db3.JPG)

**Comment by longzhiwen888** [comment]
我感觉是你配置文件的start_date和end_date的格式问题吧，我那个是年月日的，你是不是带上小时和分钟了

**Comment by longzhiwen888** [comment]
看截图你登陆时成功的，还有你不要把程序放到桌面上。你这个执行路径 Bob Jing中间还有空格，这个容易出问题，最好是把程序放到d盘或者其他地方。路径中有中文或者空格要避免出现

**Comment by jingbo1602** [comment]
好的我把程序换个位置再试试，时间我设置的如下，应该没错啊

[config]
# 要启用的浏览器driver, 因为有些人PhantomJS或者Chrome配置可能有问题，默认使用Firefox(容易配置).
# 具体参考selenium的浏览器环境配置
browser_driver = Firefox

# 百度用户名
user_name = xxxxxxx
# 百度密码
password = xxxxxx
# 百度登陆链接
login_url = https://passport.baidu.com/v2/?login&tpl=mn&u=http%3A%2F%2Fwww.baidu.com%2F

# 一周
one_week_trend_url = http://index.baidu.com/?tpl=trend&type=0&area={area}&time=12&word={word}
# 区间
time_range_trend_url = http://index.baidu.com/?tpl=trend&type=0&area={area}&time={start_date}|{end_date}&word={word}
# api
all_index_url = http://index.baidu.com/Interface/Search/getAllIndex/?res={res}&res2={res2}&startdate={start_date}&enddate={end_date}

# 图片信息的api
index_show_url = http://index.baidu.com/Interface/IndexShow/show/?res={res}&res2={res2}&classType=1&res3[]={enc_index}&className=view-value&{t}

# 判断登陆状态的地址
user_center_url = http://i.baidu.com/
# 判断登陆的标记
login_sign = http://passport.baidu.com/?logout
# 线程数
num_of_threads = 40
# 关键词index的区间开始
start_date = 2013-01-01# 关键词index的区间结束
end_date = 2013-12-31

# 输出的文件夹路径
out_file_path = C:\Python\data\out
# 保存cookie的文件名
cookie_file_path = C:\Python\data\cookie.txt
# 关键词任务的文件路径，可以自定义
keywords_task_file_path = C:\Python\task.txt
# 输出文件名的编码 (windows平台应该是gbk编码)
file_name_encoding = utf-8

# 要获取趋势的类别，默认是三种趋势都获取。all代表整体趋势，pc代表PC趋势, wise代表移动趋势
index_type_list = all,pc,wise

# 关键词地区, 具体城市code参见city.py, 此例为采集全国和北京
area_list = 0,514

**Comment by longzhiwen888** [comment]
我感觉是你那个配置文件的问题，你那个地方换行了吗？日期旁边的注释

**Comment by longzhiwen888** [comment]
# 线程数
num_of_threads = 40
# 关键词index的区间开始
start_date = 2016-09-15
# 关键词index的区间结束
end_date = 2016-09-30

**Comment by longzhiwen888** [comment]
你把配置文件整理一下吧，注释最好单独一行，不要跟配置项一行，要不程序处理可能有问题

**Comment by longzhiwen888** [comment]
问题应该可以解决了吧

**Comment by jingbo1602** [comment]
好的，这个问题解决了，进入了百度指数，但是进入了一个错误的循环，如图，不断在访问。
![error2](https://cloud.githubusercontent.com/assets/24266451/20779685/fec71038-b7b0-11e6-9af5-1140a5279945.JPG)

**Comment by longzhiwen888** [comment]
那你到那个位置在get之前，打印一下那个url呢，看看url有问题吗？是不是你上面的配置文件也有问题，注释的问题

**Comment by jingbo1602** [comment]
配置文件都把注释整理了一下，您说的url是哪一条？我没看懂……

**Comment by jingbo1602** [comment]
哦，我看到了，正在看

**Comment by longzhiwen888** [comment]
baidu_index/browser.py 的118行，self.browser.get(url)之前加一句 print(url),打印一下看看这个url是不是一个正常的url，调试嘛，我之前也没有遇到你这个问题

**Comment by jingbo1602** [comment]
print(url)
 self.browser.get(url)
![error3](https://cloud.githubusercontent.com/assets/24266451/20780002/328e4b6e-b7b3-11e6-89bd-fc07bd75f974.JPG)

**Comment by jingbo1602** [comment]
真是辛苦您了。是最下面这个url吧

**Comment by longzhiwen888** [comment]
嗯，是那个url，现在报的是你PPval没有值，一般正常运行了js都会有值得啊

**Comment by jingbo1602** [comment]
so……我应该怎么弄？看来没有正常运行……

**Comment by longzhiwen888** [comment]
你浏览器有正常的指数吗？看看在浏览器的控制台打印 PPval有值吗

**Comment by longzhiwen888** [comment]
之前也有人说过这个问题，我自己没有遇到过，也不好解决。我感觉也有可能是你浏览器还没有加载完js，这样吧，你在baidu_index/browser.py 的118行，self.browser.get(url)之后加一个 time.sleep(10)看看能好吗

**Comment by jingbo1602** [comment]
浏览器不断在刷新，感觉像是加载速度是不是跟不上，嗯，我试一试

**Comment by longzhiwen888** [comment]
嗯，你如果自己用火狐浏览器打开没有问题就好，可能是网络不好导致加载慢。

**Comment by jingbo1602** [comment]
还是同样的报错，每次启动firxfox的时候左上角都有这个，是不是浏览器的问题？
![error6](https://cloud.githubusercontent.com/assets/24266451/20780478/567f1eb0-b7b6-11e6-8c2f-9138da0baf5f.JPG)

**Comment by longzhiwen888** [comment]
我也不是太清楚，要不你就用chrome浏览器，chrome浏览器的话要下载那个驱动

**Comment by jingbo1602** [comment]
好的我去下载chrome driver再试试。您那边这个程序运行都没问题是吗，输出结果大概是什么样子的？

**Comment by longzhiwen888** [comment]
我这边平常也是用的chrome，输出最后是到excel里面

**Comment by jingbo1602** [comment]
大神！成功了，chrome可以！

**Comment by jingbo1602** [comment]
输出了6个excel，应该是对应全国地区和北京地区 pc+移动+整体的趋势吧？
![default](https://cloud.githubusercontent.com/assets/24266451/20780938/182affea-b7ba-11e6-8f54-f65b39e2c870.JPG)

**Comment by longzhiwen888** [comment]
成功了就好，那我以后还是推荐用chrome吧，看来firefox有点坑

**Comment by jingbo1602** [comment]
大神，如果以后我的boss如果用了您的工具，我会帮您要credit。也许有个第n作者……无以为报！

**Comment by longzhiwen888** [comment]
嗯，是的，你那个文件名乱码了，file_name_encoding 在配置文件里面改成gbk吧，windows用gbk

**Comment by longzhiwen888** [comment]
好的，客气了

**Comment by jingbo1602** [comment]
好的，乱码没了。再次感谢！耽误您好多时间，真是麻烦啦！祝您身体健康！
