### ISSUE TITLE
请问您的百度指数爬取工具开发完毕了么？

### ISSUE THREAD

**Issue by Luciferlol** [longzhiwen888/fetch_baidu_index#2]
您好，
我是个业余的python程序员，现在需要搞点百度指数用于数据分析。
我看到了您的百度指数爬取项目，但是不知道您的开发是否已经完成。如果已完成，我不知道怎么跑。。。
如蒙赐教，不胜感激！

**Comment by Luciferlol** [comment]
现在已经知道需要在configuration里填写账号密码，在test文件添加关键词，运行test；
然后又有个新问题：如何采集全部数据而不是仅7天？

**Comment by longzhiwen888** [comment]
采集全部的数据需要改接口，我最近没有更新过项目呢

**Comment by longzhiwen888** [comment]
我以为没有人关注呢，就没有改过

**Comment by longzhiwen888** [comment]
新版本基本是开发完成了，老版本只是实现了基本的核心功能

**Comment by Luciferlol** [comment]
好棒！
看到代码更新了开心死，我去看新版了。

**Comment by npsngs** [comment]
你好，请问你在抓取指数数据的时候是否遇到过账户访问太频繁和关键词不提供数据的限制呢?
