### ISSUE TITLE
windows 存储execl 中文字符乱码

### ISSUE THREAD

**Issue by ijackwu** [longzhiwen888/fetch_baidu_index#21]
如题

**Comment by longzhiwen888** [comment]
你修改了配置文件中的编码了吗

**Comment by longzhiwen888** [comment]
main.py 75行的encoding，你打印一下是什么编码？跟你的task.txt文件编码是一致的吗？有时候chardet这个玩意不好使

**Comment by ijackwu** [comment]
表达错误，应该是 excel 中文文件名乱码，excel中的内容没有问题。

**Comment by ijackwu** [comment]
>  file_name = file_name.encode(
>         ini_config.file_name_encoding, 'ignore'
>  )

注释了 main.py 95-97行就中文文件名没乱码了。

**Comment by longzhiwen888** [comment]
在config.ini中有file_name_encoding这个配置，没有在代码中来做判断，以后可以优化
