### ISSUE TITLE
可以考虑，无验证码登录页面？

### ISSUE THREAD

**Issue by ijackwu** [longzhiwen888/fetch_baidu_index#22]
可以考虑，无验证码登录页面，比如下面这个页面。

> http://index.baidu.com/?tpl=trend&word=%B2%E2%CA%D4%CD%F8%CB%D9

![image](https://cloud.githubusercontent.com/assets/12708015/25272949/5a999e56-26bc-11e7-8234-e257adece033.png)

**Comment by longzhiwen888** [comment]
这个页面没有验证码吗？应该是有的吧

**Comment by ijackwu** [comment]
真滴么有，亲测 @longzhiwen888

**Comment by longzhiwen888** [comment]
ok,那我以后拿这个试试，这个问题等我弄好了再关吧

**Comment by ijackwu** [comment]
## browser.py 修改下 TANGRAM__  开头字段就行了 
>         while 1:
>             try:
>                 user_name_obj = self.browser.find_element_by_id(
>                     'TANGRAM__PSP_4__userName'
>                 )
>                 break
>             except:
>                 logger.error(traceback.format_exc())
>                 time.sleep(1)
>         user_name_obj.send_keys(user_name)
>         ps_obj = self.browser.find_element_by_id('TANGRAM__PSP_4__password')
>         ps_obj.send_keys(password)
>         sub_obj = self.browser.find_element_by_id('TANGRAM__PSP_4__submit')
>         sub_obj.click()


## config.ini 

> 登录地址修改成  http://zhanzhang.baidu.com/

完事！谢谢了

**Comment by ijackwu** [comment]
@longzhiwen888 关闭浏览器cookie失效，得删掉再一次登录才行，搞不定了

**Comment by longzhiwen888** [comment]
你看看我最新的代码

**Comment by ijackwu** [comment]
已经解决！3Q
