### ISSUE TITLE
建议加一个，验证码判断，然后自动休眠

### ISSUE THREAD

**Issue by ijackwu** [longzhiwen888/fetch_baidu_index#26]
采集100个词左右就会出现验证码，然后过一段时间才会解封。

**Comment by longzhiwen888** [comment]
我觉得有必要的话降低一下请求的频率。你可以通过增大配置文件中的browser_sleep，降低线程数num_of_threads来尽量避免验证码。我没有试过大批量的导出数据

**Comment by ijackwu** [comment]
好的，感谢楼主
