### ISSUE TITLE
偶尔会出现的问题……

### ISSUE THREAD

**Issue by jingbo1602** [longzhiwen888/fetch_baidu_index#27]
![default](https://cloud.githubusercontent.com/assets/24266451/25879474/7679ef20-3564-11e7-863e-85dbec578f7e.JPG)

**Comment by longzhiwen888** [comment]
可能是你task.txt中关键词的编码问题吧

**Comment by jingbo1602** [comment]
很奇怪，就是txt里面两个字的词语都很顺，碰到一个字的关键词或者英文，就会跳错，但是每一个词单个运行都能跑，就是连起来肯定报错，只能一个一个跑……
