### ISSUE TITLE
出现验证码

### ISSUE THREAD

**Issue by yunle8** [longzhiwen888/fetch_baidu_index#28]
突然有好多失败的，然后就在服务器上截了个图，发现有验证码了。

![image](https://cloud.githubusercontent.com/assets/12691748/26774407/b5944bda-4a02-11e7-8263-4b468548c68d.png)

**Comment by longzhiwen888** [comment]
可能是访问频繁了吧

**Comment by tashuiwuhen** [comment]
我也遇到了验证码的问题，我是5个学校一跑，跑了50多个学校后就出现验证码，应该是访问频繁的问题，请问怎么自动识别验证码？

**Comment by longzhiwen888** [comment]
自动识别验证码有难度啊，一般验证码比较复杂

**Comment by longzhiwen888** [comment]
也只能降低访问频率，避免出现验证码了。或者你用一堆高匿代理访问
