### ISSUE TITLE
伪登录部分应该存在问题

### ISSUE THREAD

**Issue by w821881341** [longzhiwen888/fetch_baidu_index#3]
我运行以后一直报：

> [I 2016-06-22 17:18:17,243 browser:86] 请确保能够成功登陆百度，输入你的账号和密码，有验证码要手动输入一下

**Comment by longzhiwen888** [comment]
你的账号密码要修改一下，在config.py里面

**Comment by longzhiwen888** [comment]
其实用Firefox模式比较好，可以手动输入验证码，我在老版本默认使用了PhantomJS，感觉登陆那里不够直观

**Comment by longzhiwen888** [comment]
注意在登陆的时候，要修改配置文件中的账号信息。还有登陆时可能会遇到验证码，这种情况下最好启用火狐或者chrome浏览器输入验证码
