### ISSUE TITLE
请求解决登录验证码的问题。

### ISSUE THREAD

**Issue by newsta** [longzhiwen888/fetch_baidu_index#31]
今天使用程序的时候突然报错，发现即使输入账号和密码也无法进入百度指数的界面，主要是因为百度账号现在登录需要一个验证码， @longzhiwen888 ，请问能否帮助解决下。谢谢。

**Comment by longzhiwen888** [comment]
验证码这个可以手动填写，原本我最开始是手动填写完验证码后才走后续流程的

**Comment by longzhiwen888** [comment]
代码已经变更，有时间大家试试看
