### ISSUE TITLE
浏览器登陆有点小问题，修改了登陆之后，爬取出现账号被封！请问有解决办法吗？

### ISSUE THREAD

**Issue by TPF2017** [longzhiwen888/fetch_baidu_index#37]
提示暂无相关数据

**Comment by TPF2017** [comment]
应该是百度设置了爬取限制，现在没办法爬取指数了

**Comment by microly** [comment]
百度指数不会封号的，这个不是api，就是浏览器打开网页。百度不会限制你看他的网页啊。
只要你打开网页的频率不是太crazy，^_^~

做个随机数吧，间隔随机几秒打开一次，肯定没问题。

**Comment by GeniusLight** [comment]
调慢爬取速度
我做的修改是
在browser.py中，线程执行延时
#[pool.putRequest(req) for req in req_list]
for req in req_list:
    time.sleep(20)
    pool.putRequest(req)
pool.wait()
在config.ini中把线程改成一个
# 线程数
num_of_threads = 1


但是延时20s还是可能出现爬取不到数据，这个时候可以让程序继续跑，跑一段时间就有数据了。至于没有数据的，在excel中会显示值为0,并且是值右对齐的（正常值是左对齐），你可以后期重新爬那个没有数据时间段的。通过分析日志也可以定位到没爬取到数据的日期，重新爬吧！


以上方法就是爬取数据会很慢。
发自网易邮箱大师
在2018年2月2日 16:43，TPF2017<notifications@github.com> 写道：

提示暂无相关数据

**Comment by TPF2017** [comment]
好的，谢谢，但是我两个账号现在都已经看不到百度指数的数据了，只能再弄一个账号试一试了，我要爬很多数据啊。
不是爬不到数据的问题，是刷新了几次网页之后它就不让看百度指数的数据了。

**Comment by TPF2017** [comment]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\threadpool.py", line 158, in run
    result = request.callable(*request.args, **request.kwds)
  File "D:\TPF\python_work\financial_risk_events\fetch_baidu_index-master\baidu_index\browser.py", line 111, in get_one_day_index
    keyword, type_name, area, date, value
UnboundLocalError: local variable 'value' referenced before assignment
修改了
num_of_threads = 1
请问这个怎么解决？

**Comment by GeniusLight** [comment]
这是因为你没办法爬取到数据报的错，没关系，程序还是在继续运行吧。一般不能爬取之后要十几分钟才行吧。




发自网易邮箱大师
在2018年2月2日 17:10，TPF2017<notifications@github.com> 写道：

Traceback (most recent call last):
File "C:\Python27\lib\site-packages\threadpool.py", line 158, in run
result = request.callable(*request.args, **request.kwds)
File "D:\TPF\python_work\financial_risk_events\fetch_baidu_index-master\baidu_index\browser.py", line 111, in get_one_day_index
keyword, type_name, area, date, value
UnboundLocalError: local variable 'value' referenced before assignment
修改了
num_of_threads = 1
请问这个怎么解决？

**Comment by longzhiwen888** [comment]
这个你们自己看看源码改吧

**Comment by longzhiwen888** [comment]
我创建这个项目其实主要是把这个抓取百度指数的思路发布出来。性能问题是有的。一直没时间再维护
