### ISSUE TITLE
版主在吗，主要的browser模块能不能再多写点备注啊，新手不大看得懂啊（哭）

### ISSUE THREAD

**Issue by zilingseu** [longzhiwen888/fetch_baidu_index#7]
我是学通信出身的，没有js/前端的基础，browser这个模块很多地方都完全搞不懂啊，，，，希望能在这个模块能多点备注（最好每行都有~心里这么想。。），谢谢大神了！

**Comment by zilingseu** [comment]
主要是怎么获取每日指数的截图   不太清楚具体的思路  不知道是怎么实现的

**Comment by longzhiwen888** [comment]
我加点注释吧

**Comment by zilingseu** [comment]
谢谢版主

**Comment by zilingseu** [comment]
谢谢版主，连怕带滚地总算是有点懂了，以后还有问题还望不吝赐教。

**Comment by zilingseu** [comment]
谢谢斑竹的注释，斑竹你是怎么知道image的api的最后一个参数是时间戳的？

**Comment by longzhiwen888** [comment]
我也记不清了，这些api也都是我抓包抓来的。你用火狐的httpfo插件或者windows下用fidller就可以抓包了。一般来说异步加载的数据都是要抓包的。
