### ISSUE TITLE
Bug: create index value image data is half-baked when the image value greater than one hundred thousand(100K) 

### ISSUE THREAD

**Issue by yuany** [longzhiwen888/fetch_baidu_index#8]
I am using your project to scrape Baidu index value, it is very useful for me,  thanks so much you to open it on github, but I found the program will recognize the index value incorrectly when the value greater than 100k, like this:
a bad case as below:

![image](https://cloud.githubusercontent.com/assets/2010992/17075870/5b62d0f0-50d4-11e6-8041-3523f9ce9e1d.png)

the full image shoue be:

![image](https://cloud.githubusercontent.com/assets/2010992/17075874/89062822-50d4-11e6-940b-708a3e9d2206.png)

After my investigate and debug I found the bug caused by your set the size of final index value image

File: \baidu_index\img_util.py

`end_img = Image.new('RGB', (50, new_img.size[1]))`
 should change the **50** to big value to fix the issue for example:
`end_img = Image.new('RGB', (100, new_img.size[1]))`

**Comment by longzhiwen888** [comment]
Thank you for your feedback, the width of 50 is also felt enough to write this, and changed to 100, then there is no problem. I modified it in the project.
