### ISSUE TITLE
4.修改task.txt，这是关键词的任务列表，一行一个。注意这里面的编码是utf-8的，最好也别带bom头，免得出问题

### ISSUE THREAD

**Issue by endlessss** [longzhiwen888/fetch_baidu_index#9]
4.修改task.txt，这是关键词的任务列表，一行一个。注意这里面的编码是utf-8的，最好也别带bom头，免得出问题

这句话是怎么理解？为什么我直接在task.txt里面输入其他的中文不可以抓取，你的又可以？
出现信息：
Traceback (most recent call last):
  File "C:\Python27\baidu_index\browser.py", line 194, in get_baidu_index
    keyword, start_date, end_date, type_name
  File "C:\Python27\baidu_index\browser.py", line 104, in get_baidu_index_by_date_range
    word=urllib.quote(keyword.encode('gbk'))
UnicodeEncodeError: 'gbk' codec can't encode character u'\ufeff' in position 0: illegal multibyte sequence

**Comment by endlessss** [comment]
表达不对，不是不能抓取，而是抓取是为什么是乱码的问题，以至于入库时，编码也出现问题

**Comment by longzhiwen888** [comment]
就是中文乱码嘛，不知道你是不是改了我的代码，task.txt里面如果是utf8编码的，就不会有问题。main.py里面读取出来task.txt的文件内容后会以utf8编码decode,我写入excel的时候是用的unicode编码写入的。按我的代码，你那个task.txt文件按utf8编码存储就没有问题吧。

**Comment by endlessss** [comment]
conn = pymysql.connect('127.0.0.1', port=3306, user = 'root', passwd = '',db='baiduzhishu',charset='utf8')
    cur = conn.cursor()
    for result in data_list:
        print(result)
        cur.execute('insert into baiduzhishu_table (keyword,date,type_name,zhishu) values(%s,%s,%s,%s)',result)
        conn.commit() 
这是在写入表格的那个方法，同时想着一起写入数据库，不知道怎么解决unicode编码问题，博主能帮忙？

**Comment by endlessss** [comment]
[I 2016-07-25 17:10:10,733 main:16] 请确保你填写的账号密码能够成功登陆百度
[I 2016-07-25 17:10:26,005 browser:96] date:2016-06-29, value:1,933
[I 2016-07-25 17:10:26,032 browser:96] date:2016-06-30, value:2,158
(u'\u771f\u9f99', '2016-06-29', 'all', '1933')
Traceback (most recent call last):
  File "C:\Python27\baidu_index\main.py", line 51, in main
    write_excel(file_path, data_list)
  File "C:\Python27\baidu_index\main.py", line 80, in write_excel
    cur.execute('insert into baiduzhishu_table (keyword,date,type_name,zhishu) values(%s,%s,%s,%s)',result)
  File "C:\Python27\lib\site-packages\pymysql\cursors.py", line 97, in execute
    escaped_args = tuple(conn.escape(arg) for arg in args)
  File "C:\Python27\lib\site-packages\pymysql\cursors.py", line 97, in <genexpr>
    escaped_args = tuple(conn.escape(arg) for arg in args)
  File "C:\Python27\lib\site-packages\pymysql\connections.py", line 579, in escape
    return escape_item(obj, self.charset)
  File "C:\Python27\lib\site-packages\pymysql\converters.py", line 31, in escape_item
    encoder = encoders[type(val)]
KeyError: <type 'unicode'>
写入数据库前，博主能否帮解决掉unicode和utf8问题，新手面对编码问题无从下手......

**Comment by longzhiwen888** [comment]
其实也不复杂吧，data_list你不要用这个data_list.append((keyword_unicode, date, type_name, value))。

用data_list.append((keyword, date, type_name, value))试试。前提是你那个task.txt是utf8编码保存的额

**Comment by endlessss** [comment]
还是不行，刚刚试过，解决一天的编码问题了。能麻烦博主再帮写个数据库？task.txt那个问题解决了。

**Comment by endlessss** [comment]
改成data_list.append((keyword, date, type_name, value))之后贴个错误：
[I 2016-07-25 17:38:27,798 main:16] 请确保你填写的账号密码能够成功登陆百度
[I 2016-07-25 17:38:43,573 browser:96] date:2016-06-29, value:1,933
[I 2016-07-25 17:38:43,575 browser:96] date:2016-06-30, value:2,158
Traceback (most recent call last):
  File "C:\Python27\baidu_index\main.py", line 51, in main
    write_excel(file_path, data_list)
  File "C:\Python27\baidu_index\main.py", line 74, in write_excel
    wb.save(excel_file)
  File "C:\Python27\lib\site-packages\xlwt\Workbook.py", line 696, in save
    doc.save(filename_or_stream, self.get_biff_data())
  File "C:\Python27\lib\site-packages\xlwt\Workbook.py", line 660, in get_biff_data
    shared_str_table   = self.__sst_rec()
  File "C:\Python27\lib\site-packages\xlwt\Workbook.py", line 622, in __sst_rec
    return self.__sst.get_biff_record()
  File "C:\Python27\lib\site-packages\xlwt\BIFFRecords.py", line 77, in get_biff_record
    self._add_to_sst(s)
  File "C:\Python27\lib\site-packages\xlwt\BIFFRecords.py", line 92, in _add_to_sst
    u_str = upack2(s, self.encoding)
  File "C:\Python27\lib\site-packages\xlwt\UnicodeUtils.py", line 50, in upack2
    us = unicode(s, encoding)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 0: ordinal not in range(128)

**Comment by longzhiwen888** [comment]
我给你改那行是让你执行sql的，你还执行我那个保存excel的肯定会报错

**Comment by longzhiwen888** [comment]
你保存sql的那个，最好是给我个完整的错误堆栈信息

**Comment by endlessss** [comment]
因为我是在保存excel那里添加的数据库，所以编码的转换一直是个问题

**Comment by longzhiwen888** [comment]
我晕，你用你的代码随便把一个中文存进去看看数据库会报错吗？跟我的这个项目应该没有什么关系。

**Comment by endlessss** [comment]
嗯嗯，是的，不过不会怎么把unicode转换utf8再入库，博主能解决？当然直接入库是没有问题的，再多写个方法就行，但是就是想解决这个问题。

**Comment by endlessss** [comment]
File "C:\Python27\baidu_index\main.py", line 65, in <module>
  main()
File "C:\Python27\baidu_index\main.py", line 60, in main
  cur.execute('insert into baiduzhishu_table (keyword,date,type_name,zhishu) values(%s,%s,%s,%s)',result)
File "C:\Python27\Lib\site-packages\pymysql\cursors.py", line 108, in execute
  query = query.encode(charset)

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 70: ordinal not in range(128)
博主能帮解决？

**Comment by longzhiwen888** [comment]
你把你的代码还有数据库的那张表dump一下给我吧，省得我再改了。我在我的环境下测试一下

**Comment by longzhiwen888** [comment]
我在我这里测试一下存入数据库吧，按道理应该没有太大问题的

**Comment by endlessss** [comment]
谢谢万能的博主！原谅从没做过python的新手第一次遇到这种不能理解的问题，唉...谢谢理解
以下是main.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os
import traceback
import pymysql
import traceback
import xlwt

from baidu_index.browser import BaiduBrowser
from baidu_index.utils.log import logger
import baidu_index.config as config


def main():
    logger.info(u'请确保你填写的账号密码能够成功登陆百度')
    # s = BaiduBrowser(cookie_json='{"name": "1"}')
    # cookie_json = s.cookie_json
    # s.close()
    s = BaiduBrowser()

    fp = open(config.keywords_task_file_path, 'rb')
    task_list = fp.readlines()
    fp.close()

    root = os.path.dirname(os.path.realpath(__file__))
    result_folder = os.path.join(root, config.out_file_path)
    if not os.path.exists(result_folder):
        os.makedirs(result_folder)

    type_list = config.index_type_list
    for keyword in task_list:
        try:
            keyword = keyword.strip()
            if not keyword:
                continue
            keyword_unicode = keyword.decode('utf-8')
            for type_name in type_list:
                baidu_index_dict = s.get_baidu_index(
                    keyword_unicode, type_name
                )
                date_list = sorted(baidu_index_dict.keys())

                file_name = '%s_%s.xls' % (keyword, type_name)
                file_path = os.path.join(result_folder, file_name)

                data_list = []
                for date in date_list:
                    value = baidu_index_dict[date]
                    data_list.append((keyword, date, type_name, value))
                write_excel(file_path, data_list)         
        except:
            print traceback.format_exc()
     
    


def write_excel(excel_file, data_list):
    wb = xlwt.Workbook()
    ws = wb.add_sheet(u'工作表1')
    row = 0
    ws.write(row, 0, u'关键词')
    ws.write(row, 1, u'日期')
    ws.write(row, 2, u'类型')
    ws.write(row, 3, u'指数')
    row = 1
    for result in data_list:
        col = 0
        for item in result:
            ws.write(row, col, item)
            col += 1
        row += 1

    wb.save(excel_file)
    
    conn = pymysql.connect('127.0.0.1', port=3306, user = 'root', passwd = '',db='baiduzhishu',charset='utf8')
    cur = conn.cursor()
    for result in task_list:
        print(result)
        cur.execute('insert into baiduzhishu_table (keyword,date,type_name,zhishu) values(%s,%s,%s,%s)',result)
        conn.commit()     
   


if __name__ == '__main__':
    main()

**Comment by longzhiwen888** [comment]
data_list = []
                for date in date_list:
                    value = baidu_index_dict[date]
                    save_zhishu((keyword_unicode, date, type_name, value))
                    data_list.append((keyword_unicode, date, type_name, value))
                write_excel(file_path, data_list)

**Comment by longzhiwen888** [comment]
data_list = []
                for date in date_list:
                    value = baidu_index_dict[date]
                    save_zhishu((keyword_unicode, date, type_name, value))
                    data_list.append((keyword_unicode, date, type_name, value))
                write_excel(file_path, data_list)

**Comment by longzhiwen888** [comment]
import pymysql.cursors


def get_mysql_conn():
    return pymysql.connect(
        host='127.0.0.1',
        user='dev',
        passwd='123456',
        db='test',
        charset='utf8',
        cursorclass=pymysql.cursors.DictCursor
    )


def save_zhishu(result):
    conn = get_mysql_conn()
    cursor = conn.cursor()
    sql = 'insert into baiduzhishu_table (keyword,date,type_name,zhishu) values(%s,%s,%s,%s)'
    cursor.execute(sql, result)
    conn.commit()
    conn.close()

**Comment by longzhiwen888** [comment]
你把缩进处理一下，我这里测试了一下没有问题啊。可能我系统跟你不一样的原因？我这里是mac。我刚才给你贴的那两段，你能看出来吧，第一段是加了一个save_zhishu的调用

**Comment by endlessss** [comment]
好的，努力去试试！谢谢博主！

**Comment by longzhiwen888** [comment]
你看看你的数据库编码是utf8的吧？别整个gbk的。存mysql的时候，中文用unicode编码的应该是没有太大问题的。读取出来的还经常是unicode的

**Comment by endlessss** [comment]
是的，由于之前utf8一直都无法解决还改成gbk过，发现应该不是这个问题又改了回去，其他地方的编码都改过了一遍。还把table删了重建也依旧没有解决问题。现在确定项目全部都是utf8的。

**Comment by Boom247** [comment]
博主，求教啊！为什么我改了config.py里的日期之后，导出的数据还是2016-06-01到2016-06-30呀？
# 关键词index的区间开始
start_date = '2016-06-15'
# 关键词index的区间结束S
end_date = '2016-06-30'
这是我改过后的，不知道错在哪里了，运行了好多遍都不行...

**Comment by longzhiwen888** [comment]
我看你在别处提问了，已经好了是吧
